python_thrift_library(
    name='A',
    sources=[
        'A.thrift',
    ],
    dependencies=[
        ':B',
        ':C',
    ]
)

python_thrift_library(
    name='B',
    sources=[
        'B.thrift',
    ]
)

python_thrift_library(
    name='C',
    sources=[
        'C.thrift',
    ]
)
